"""empty message

Revision ID: af3111e9da20
Revises: 82a96273103d
Create Date: 2022-05-11 22:58:40.536224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3111e9da20'
down_revision = '82a96273103d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('duration', sa.String(length=128), nullable=False))
    op.drop_column('events', 'durationi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('duration', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('events', 'duration')
    op.drop_table('customers')
    # ### end Alembic commands ###
