"""empty message

Revision ID: 779c9fcc78be
Revises: 6813ec432b09
Create Date: 2022-05-11 21:57:12.503137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779c9fcc78be'
down_revision = '6813ec432b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('locations', sa.String(length=128), nullable=False),
    sa.Column('numb_pers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
