"""empty message

Revision ID: 94241f1a21c4
Revises: 779c9fcc78be
Create Date: 2022-05-11 22:23:01.898109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94241f1a21c4'
down_revision = '779c9fcc78be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('appt_date', sa.Date(), nullable=False),
    sa.Column('duration', sa.String(length=128), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('photo_shoot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['photo_shoot_id'], ['photo_shoots.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
