"""empty message

Revision ID: 0a129216179c
Revises: af3111e9da20
Create Date: 2022-05-11 23:25:11.292194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a129216179c'
down_revision = 'af3111e9da20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers_events',
    sa.Column('price', sa.String(length=128), nullable=False),
    sa.Column('photo_type', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'event_id')
    )
    op.alter_column('customers', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('customers_events')
    # ### end Alembic commands ###
